#!/usr/bin/env bash
# install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw enable
sudo ufw allow 'nginx HTTP'
sudo chmod -R 777 *
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
