#!/usr/bin/env bash
# install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw enable -y
sudo ufw allow 'nginx HTTP' -y
echo "Holberton School" >> ~/index | cp ~/index /var/www/demo/
