#!/usr/bin/env bash
# iredirect nginx
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw enable
sudo ufw allow 'nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed '43,47 s/location / {.*}$/location / {https://www.youtube.com/watch?v=Gbz2C2gQREI}' /etc/nginx/sites-enabled/default
sudo service nginx restart
