#!/usr/bin/env bash
# iredirect nginx
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw enable
sudo ufw allow 'nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
server	{rewrite ^35.227.56.113/redirect_me$ https://www.youtube.com/watch?v=Gbz2C2gQREI permanent}
sudo service nginx restart
