#!/usr/bin/env bash
# displays pings an IP address passed as an argument.

filename="IP_ADDRESS"

if [ -e $filename ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c5
fi
