#!/usr/bin/env bash
# loop and echo To infinity and beyond indefinitely.

echo $$ > /var/run/holbertonscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo Y U no love me?!" SIGINT
    trap 'echo "I hate the kill command" && exit && rm /var/run/holbertonscript.pid' SIGTERM
    trap 'rm /var/run/holbertonscript.pid && exit' SIGQUIT
    touch /var/run/holbertonscript.pid
done
