#!/usr/bin/env bash
# loop and echo To infinity and beyond indefinitely.

echo $$ > touch /var/run/holbertonscript.pid
trap "echo I am invincible!!!" 15
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid" 3 15
while true
do
    echo "To infinity and beyond"
    sleep 2
done
