#!/usr/bin/env bash
# loop and echo To infinity and beyond indefinitely.

echo $$ > touch /var/run/holbertonscript.pid
trap "echo I hate the kill command" SIGTERM
trap "exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid | exit" 3 15
trap "exit" 3 15
touch /var/run/holbertonscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
done
