#!/usr/bin/env bash
# list all directories
n=1

for i in {1..20}
do
    if (( $n%3=0 ))
        then
            echo "Fizz"
        elif (( $n%5=0 ))
        then
            echo "Buzz"
        elif (( $n%3=0 && $n%5=0 ))
        then
            echo "FizzBuzz"
        else
            echo "$n"
        fi
    (( n++ ))
done
