#!/usr/bin/env bash
# change ip addresses in host dir (not mine)

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8	facebook.com" >> /etc/hosts
cp -f ~/hosts.new /etc/hosts
