.PHONY: all generate say_hello clean

all: say_hello generate

say_hello:
	@echo "Hello World"
generate:
	@echo "make 10 empty files."
	touch file - {1..10}.txt
clean:
	@echo "clean files..."
	rm *.txt
